### ISSUE TITLE
can't run runners

### ISSUE THREAD

**Issue by ferronsnicola** [liznerski/fcdd#18]
Hello, thank you for sharing this project.
I can't run the runner and I have this output after following all the instructions:

Plotting ROC for completed classes up to 0...
Traceback (most recent call last):
  File "runners/run_custom.py", line 37, in <module>
    runner.run()
  File "..\fcdd-master\venv\lib\site-packages\fcdd\runners\bases.py", line 203, in run
    self.run_classes(**vars(self.args))
  File "..\fcdd-master\venv\lib\site-packages\fcdd\runners\bases.py", line 222, in run_classes
    it, **kwargs
  File "..\fcdd-master\venv\lib\site-packages\fcdd\runners\bases.py", line 182, in run_seeds
    this_viz_ids, **kwargs
  File "..\fcdd-master\venv\lib\site-packages\fcdd\runners\bases.py", line 101, in run_one
    **kwargs
  File "..\fcdd-master\venv\lib\site-packages\fcdd\training\setup.py", line 106, in trainer_setup
    noise_mode, online_supervision, nominal_label, oe_limit, logger=logger
  File "..\fcdd-master\venv\lib\site-packages\fcdd\datasets\__init__.py", line 62, in load_dataset
    oe_limit=oe_limit, logger=logger, nominal_label=nominal_label
  File "..\fcdd-master\venv\lib\site-packages\fcdd\datasets\image_folder.py", line 90, in __init__
    mean, std = self.extract_mean_std(trainpath, normal_class)
  File "..\fcdd-master\venv\lib\site-packages\fcdd\datasets\image_folder.py", line 188, in extract_mean_std
    for x, _ in loader:
  File "..\fcdd-master\venv\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "..\fcdd-master\venv\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init_
_
    reduction.dump(process_obj, to_child)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'ADImageFolderDataset.extract_mean_std.<locals>.<lambda>'

(venv) ..\fcdd-master\python\fcdd>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

Could you help me, please?
Thank you

**Comment by liznerski** [comment]
Hey. Thanks for your report. This seems to be a similar issue as in #2 and is due to windows having problems with pickling certain functions. We fixed such problems in the windows branch; however, the custom runner is not available there yet. I will implement a solution and merge the two branches in a couple of weeks, which should fix your problem. Meanwhile, you can either use Linux or try to move the **ADImageFolderDataset.extract_mean_std** function out of the class.

**Comment by ferronsnicola** [comment]
oh thank you, i didn't find it before. on linux I don't have this issue.
thank you
