### ISSUE TITLE
Multiple classes with one-vs-rest training raises AttributeError

### ISSUE THREAD

**Issue by layadas** [liznerski/fcdd#60]
I have a dataset that is organised as follows:
```
Train images:
custom/train/class0/
custom/train/class1/
custom/train/class2/

Train maps:
custom/train_maps/class0/
custom/train_maps/class1/
custom/train_maps/class2/

Test images:
custom/test/class0/
custom/test/class1/
custom/test/class2/

Test maps:
custom/test_maps/class0/
custom/test_maps/class1/
custom/test_maps/class2/
```
I use the following command for training the model:
`python runners/run_custom.py --supervise-mode other --blur-heatmaps -gtms -ovr`
It starts training the model for 200 epochs, and creates a folder `normal_0` with `it_0` in it. It generates an error as follows:
```
EPOCH 199 NBAT 0000/0005 ERR 1.343491 ERR_NORMAL 2.115482 ERR_ANOMALOUS 0.550352 INFO LR ['5e-05'] ID fcdd.training.fcdd.FCDDTrainer
Test training data...
TEST 0000/0005 ID fcdd.training.fcdd.FCDDTrainer
Test test data...
TEST 0000/0002 ID fcdd.training.fcdd.FCDDTrainer NCLS (0,)
Computing test score...
##### ROC TEST SCORE 0.019260400616332822 #####
Computing GT test score...
Plotting ROC for completed classes up to 0...
Traceback (most recent call last):
  File "runners/run_custom.py", line 48, in <module>
    runner.run()
  File "C:\Users\laydas\AppData\Roaming\Python\Python38\site-packages\fcdd\runners\bases.py", line 203, in run
    self.run_classes(**vars(self.args))
  File "C:\Users\laydas\AppData\Roaming\Python\Python38\site-packages\fcdd\runners\bases.py", line 221, in run_classes
    res = self.run_seeds(
  File "C:\Users\laydas\AppData\Roaming\Python\Python38\site-packages\fcdd\runners\bases.py", line 181, in run_seeds
    res = self.run_one(
  File "C:\Users\laydas\AppData\Roaming\Python\Python38\site-packages\fcdd\runners\bases.py", line 107, in run_one
    x = trainer.test(viz_ids)
  File "C:\Users\laydas\AppData\Roaming\Python\Python38\site-packages\fcdd\training\super_trainer.py", line 94, in test
    res = self.trainer.test(specific_viz_ids)
  File "C:\Users\laydas\AppData\Roaming\Python\Python38\site-packages\fcdd\training\bases.py", line 264, in test
    sc = self.score(labels, anomaly_scores, imgs, outputs, gtmaps, grads)
  File "C:\Users\laydas\AppData\Roaming\Python\Python38\site-packages\fcdd\training\bases.py", line 377, in score
    gtmaps = self.test_loader.dataset.dataset.get_original_gtmaps_normal_class()
AttributeError: 'ImageFolderDatasetGTM' object has no attribute 'dataset'
```
I am not sure why this errors occurs - is there a problem with the command, or the dataset organisation? Thank you in advance for your help and suggestions.

**Comment by liznerski** [comment]
Hey. Thanks for reporting. That's actually just a bug ;)
Should be fixed with a97d96bdd78a02bc947fa380df03e06ebf8b0e2b.
