### ISSUE TITLE
"AssertionError: binary labels required" when unsupervised training of MVTec AD Dataset

### ISSUE THREAD

**Issue by GreatScherzo** [liznerski/fcdd#8]
<h2>🐛Bug</h2>

- Training the model using MVTec AD dataset without any Outlier Exposure seems to cause an error "AssertionError: binary labels required"
<h2>Traceback</h2>

The input command is as below:
python ./fcdd/runners/run_mvtec.py --supervise-mode unsupervised

```
......
EPOCH 1991 NBAT 0007/0014 ERR 0.000805  INFO LR ['5e-05'] ID fcdd.training.fcdd.FCDDTrainer
EPOCH 1992 NBAT 0007/0014 ERR 0.000803  INFO LR ['5e-05'] ID fcdd.training.fcdd.FCDDTrainer
EPOCH 1993 NBAT 0007/0014 ERR 0.000802  INFO LR ['5e-05'] ID fcdd.training.fcdd.FCDDTrainer
EPOCH 1994 NBAT 0007/0014 ERR 0.000803  INFO LR ['5e-05'] ID fcdd.training.fcdd.FCDDTrainer
EPOCH 1995 NBAT 0007/0014 ERR 0.000802  INFO LR ['5e-05'] ID fcdd.training.fcdd.FCDDTrainer
EPOCH 1996 NBAT 0007/0014 ERR 0.000800  INFO LR ['5e-05'] ID fcdd.training.fcdd.FCDDTrainer
EPOCH 1997 NBAT 0007/0014 ERR 0.000801  INFO LR ['5e-05'] ID fcdd.training.fcdd.FCDDTrainer
EPOCH 1998 NBAT 0007/0014 ERR 0.000801  INFO LR ['5e-05'] ID fcdd.training.fcdd.FCDDTrainer
EPOCH 1999 NBAT 0007/0014 ERR 0.000800  INFO LR ['5e-05'] ID fcdd.training.fcdd.FCDDTrainer
Test training data...
TEST 0000/0014 ID fcdd.training.fcdd.FCDDTrainer
TEST 0007/0014 ID fcdd.training.fcdd.FCDDTrainer
Plotting Many ROC for completed classes up to 0...
Traceback (most recent call last):
  File "./fcdd/runners/run_mvtec.py", line 19, in <module>
    runner.run()
  File "/usr/local/lib/python3.6/dist-packages/fcdd/runners/bases.py", line 203, in run
    self.run_classes(**vars(self.args))
  File "/usr/local/lib/python3.6/dist-packages/fcdd/runners/bases.py", line 222, in run_classes
    it, **kwargs
  File "/usr/local/lib/python3.6/dist-packages/fcdd/runners/bases.py", line 182, in run_seeds
    this_viz_ids, **kwargs
  File "/usr/local/lib/python3.6/dist-packages/fcdd/runners/bases.py", line 107, in run_one
    x = trainer.test(viz_ids)
  File "/usr/local/lib/python3.6/dist-packages/fcdd/training/super_trainer.py", line 94, in test
    res = self.trainer.test(specific_viz_ids)
  File "/usr/local/lib/python3.6/dist-packages/fcdd/training/bases.py", line 244, in test
    name='train_heatmaps',
  File "/usr/local/lib/python3.6/dist-packages/fcdd/training/bases.py", line 414, in heatmap_generation
    idx, name, imgs.shape, subdir, show_per_cls, imgs, ascores, grads, gtmaps, labels
  File "/usr/local/lib/python3.6/dist-packages/fcdd/training/bases.py", line 486, in _create_heatmaps_picture
    colorize=True, ref=balance_labels(ascores, labels, err) if norm == 'global' else ascores[idx],
  File "/usr/local/lib/python3.6/dist-packages/fcdd/training/__init__.py", line 13, in balance_labels
    assert len(lblset) == 2, 'binary labels required'
AssertionError: binary labels required
```

<h2>Expected Behaviour</h2>
Was expecting for it run test phase without any problem

<h2>Environment</h2>
Environment: Google Colab

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.4.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.5.0
[conda] Could not collect

<h2>Additional Context</h2>
I'm using linux this time, but it seems that the ram wasn't enough during the multiprocessing phase, where datas are sampled 10 times. I then turned off 'enlarge' and switched the epochs to 2000.

Thanks once again for taking your time!

**Comment by liznerski** [comment]
Once again, thanks for your report. Should be fixed now. Otherwise, feel free to reopen.

**Comment by abappu** [comment]
I checked with a custom dataset with 1 class.
I put images in "dsdir/custom/train/classX/" and "dsdir/custom/test/classX/"
executed with "python runners/run_custom.py -ovr --supervise-mode unsupervised"
It trained without an issue. During testing phase, it gave the same error.
Do you have any suggestions to solve this?

**Comment by liznerski** [comment]
Well. This will happen if no anomalous samples are available during testing. The heatmaps are generated with two kinds of normalization, "local" and "global". The latter normalizes w.r.t. the complete dataset and will throw this error if it finds no anomalous labels. Since having no ground-truth anomalies available during test time is a valid option, I changed this behavior and logged a warning instead (eb3062105e0b345f0abc4aebcbc48247bc9fcda0). This should solve your issue. 

Thanks for the report.
